//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubTran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<form action=""https://www.paypal.com/cgi-bin/webscr"" target=""_blank"" method=""post"">
<input type=""hidden"" name=""cmd"" value=""_donations"">
<input type=""hidden"" name=""business"" value=""sales@cuebiztech.com"">
<input type=""hidden"" name=""lc"" value=""US"">
<input type=""hidden"" name=""no_note"" value=""0"">
<input type=""hidden"" name=""currency_code"" value=""USD"">
<input type=""hidden"" name=""bn"" value=""PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest"">
<input type=""image"" src=""https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"" border=""0"" name=""submit"" alt=""PayPal - The safer, easier way to pay online!"">
<img alt="""" border=""0"" src=""https://www.paypalobjects.com/en_US/i/scr/pixel.gif"" width=""1"" height=""1"">
</form>")]
        public string PaypalDonate {
            get {
                return ((string)(this["PaypalDonate"]));
            }
            set {
                this["PaypalDonate"] = value;
            }
        }
    }
}
